[project]
name = "fi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[all]>=0.116.1",
    "logfire[fastapi]>=4.6.0",
    "pydantic-settings>=2.10.1",
    "pypika>=0.48.9",
]
