INSERT INTO currencies (name, code, numeric_code, symbol) VALUES
('United Arab Emirates Dirham', 'AED', 784, 'د.إ'),
('Afghan Afghani', 'AFN', 971, '؋'),
('Albanian Lek', 'ALL', 008, 'L'),
('Armenian Dram', 'AMD', 051, '֏'),
('Angolan Kwanza', 'AOA', 973, 'Kz'),
('East Caribbean Dollar', 'XCD', 951, '$'),
('Argentine Peso', 'ARS', 032, '$'),
('Australian Dollar', 'AUD', 036, '$'),
('Aruban Florin', 'AWG', 533, 'ƒ'),
('Azerbaijan Manat', 'AZN', 944, '₼'),
('Bosnia And Herzegovina Convertible Mark', 'BAM', 977, 'KM'),
('Barbados Dollar', 'BBD', 052, '$'),
('Taka', 'BDT', 050, '৳'),
('Bulgarian Lev', 'BGN', 975, 'лв'),
('Bahraini Dinar', 'BHD', 048, '.د.ب'),
('Burundi Franc', 'BIF', 108, 'FBu'),
('Bermudan Dollar', 'BMD', 060, '$'),
('Brunei Dollar', 'BND', 096, '$'),
('Bolivian Boliviano', 'BOB', 068, 'Bs.'),
('Mvdol', 'BOV', 984, ''),
('Brazilian Real', 'BRL', 986, 'R$'),
('Bahamian Dollar', 'BSD', 044, '$'),
('Bhutan Ngultrum', 'BTN', 064, 'Nu.'),
('Botswana Pula', 'BWP', 072, 'P'),
('Belarusian Ruble', 'BYN', 933, 'Br'),
('Belize Dollar', 'BZD', 084, 'BZ$'),
('CFA Franc BCEAO', 'XOF', 952, 'CFA'),
('Canadian Dollar', 'CAD', 124, '$'),
('Congolese Franc', 'CDF', 976, 'FC'),
('WIR Euro', 'CHE', 947, ''),
('Swiss Franc', 'CHF', 756, 'Fr.'),
('WIR Franc', 'CHW', 948, ''),
('Unidad De Fomento', 'CLF', 990, 'UF'),
('Chilean Peso', 'CLP', 152, '$'),
('Chinese Yuan', 'CNY', 156, '¥'),
('Colombian Peso', 'COP', 170, '$'),
('Unidad De Valor Real', 'COU', 970, ''),
('Costa Rican Colon', 'CRC', 188, '₡'),
('Cuban Peso', 'CUP', 192, '$'),
('Cape Verde Escudo', 'CVE', 132, '$'),
('Czech Koruna', 'CZK', 203, 'Kč'),
('Djibouti Franc', 'DJF', 262, 'Fdj'),
('Danish Krone', 'DKK', 208, 'kr'),
('Dominican Peso', 'DOP', 214, 'RD$'),
('Algerian Dinar', 'DZD', 012, 'د.ج'),
('Egyptian Pound', 'EGP', 818, '£'),
('Eritrean Nakfa', 'ERN', 232, 'Nfk'),
('Ethiopian Birr', 'ETB', 230, 'Br'),
('Euro', 'EUR', 978, '€'),
('Fiji Dollar', 'FJD', 242, '$'),
('Falkland Islands Pound', 'FKP', 238, '£'),
('Pound Sterling', 'GBP', 826, '£'),
('Georgian Lari', 'GEL', 981, '₾'),
('Ghana Cedi', 'GHS', 936, '₵'),
('Gibraltar Pound', 'GIP', 292, '£'),
('Gambian Dalasi', 'GMD', 270, 'D'),
('Guinean Franc', 'GNF', 324, 'FG'),
('Guatemalan Quetzal', 'GTQ', 320, 'Q'),
('Guyanese Dollar', 'GYD', 328, '$'),
('Hong Kong Dollar', 'HKD', 344, '$'),
('Honduran Lempira', 'HNL', 340, 'L'),
('Haitian Gourde', 'HTG', 332, 'G'),
('Hungarian Forint', 'HUF', 348, 'Ft'),
('Icelandic Króna', 'ISK', 352, 'kr'),
('Indian Rupee', 'INR', 356, '₹'),
('Iraqi Dinar', 'IQD', 368, 'د.ع'),
('Iranian Rial', 'IRR', 364, '﷼'),
('Jamaican Dollar', 'JMD', 388, 'J$'),
('Jordanian Dinar', 'JOD', 400, 'JD'),
('Japanese Yen', 'JPY', 392, '¥'),
('Kenyan Shilling', 'KES', 404, 'KSh'),
('North Korean Won', 'KPW', 408, '₩'),
('South Korean Won', 'KRW', 410, '₩'),
('Kuwaiti Dinar', 'KWD', 414, 'د.ك'),
('Cayman Islands Dollar', 'KYD', 136, '$'),
('Kazakhstani Tenge', 'KZT', 398, '₸'),
('Laotian Kip', 'LAK', 418, '₭'),
('Lebanese Pound', 'LBP', 422, 'ل.ل'),
('Sri Lankan Rupee', 'LKR', 144, 'Rs'),
('Liberian Dollar', 'LRD', 430, '$'),
('Lesotho Loti', 'LSL', 426, 'M'),
('Libyan Dinar', 'LYD', 434, 'ل.د'),
('Moroccan Dirham', 'MAD', 504, 'د.م.'),
('Macedonian Denar', 'MKD', 807, 'ден'),
('Malagasy Ariary', 'MGA', 969, 'Ar'),
('Malawian Kwacha', 'MWK', 454, 'MK'),
('Malaysian Ringgit', 'MYR', 458, 'RM'),
('Maldivian Rufiyaa', 'MVR', 462, 'Rf'),
('Mauritanian Ouguiya', 'MRU', 929, 'UM'),
('Mauritian Rupee', 'MUR', 480, 'Rs'),
('Mexican Peso', 'MXN', 484, '$'),
('Mexican Unidad De Inversion', 'MXV', 979, ''),
('Moldovan Leu', 'MDL', 498, 'L'),
('Mongolian Tugrik', 'MNT', 496, '₮'),
('Macanese Pataca', 'MOP', 446, 'P'),
('CFA Franc BEAC', 'XAF', 950, 'FCFA'),
('Norwegian Krone', 'NOK', 578, 'kr'),
('Nepalese Rupee', 'NPR', 524, 'Rs'),
('Nicaraguan Córdoba', 'NIO', 558, 'C$'),
('Nigerian Naira', 'NGN', 566, '₦'),
('Omani Rial', 'OMR', 512, 'ر.ع.'),
('Panamanian Balboa', 'PAB', 590, 'B/.'),
('Peruvian Sol', 'PEN', 604, 'S/.'),
('Papua New Guinean Kina', 'PGK', 598, 'K'),
('Philippine Peso', 'PHP', 608, '₱'),
('Pakistani Rupee', 'PKR', 586, 'Rs'),
('Polish Zloty', 'PLN', 985, 'zł'),
('Paraguayan Guaraní', 'PYG', 600, 'Gs'),
('Qatari Riyal', 'QAR', 634, 'ر.ق'),
('Romanian Leu', 'RON', 946, 'lei'),
('Serbian Dinar', 'RSD', 941, 'дин'),
('Russian Ruble', 'RUB', 643, '₽'),
('Rwandan Franc', 'RWF', 646, 'FRw'),
('Saudi Riyal', 'SAR', 682, 'ر.س'),
('Solomon Islands Dollar', 'SBD', 090, '$'),
('Seychellois Rupee', 'SCR', 690, 'Rs'),
('Sudanese Pound', 'SDG', 938, 'ج.س.'),
('Swedish Krona', 'SEK', 752, 'kr'),
('Singapore Dollar', 'SGD', 702, '$'),
('Saint Helena Pound', 'SHP', 654, '£'),
('Sierra Leonean Leone', 'SLE', 925, 'Le'),
('Somali Shilling', 'SOS', 706, 'Sh'),
('Surinamese Dollar', 'SRD', 968, '$'),
('South Sudanese Pound', 'SSP', 728, '£'),
('São Tomé And Príncipe Dobra', 'STN', 930, 'Db'),
-- ('Salvadoran Colón', 'SVC', 222, '₡') -- removed (obsolete)
('Syrian Pound', 'SYP', 760, '£'),
('Swazi Lilangeni', 'SZL', 748, 'E'),
('Thai Baht', 'THB', 764, '฿'),
('Tajikistani Somoni', 'TJS', 972, 'TJS'),
('Turkmenistani Manat', 'TMT', 934, 'm'),
('Tunisian Dinar', 'TND', 788, 'د.ت'),
('Tongan Paʻanga', 'TOP', 776, 'T$'),
('Turkish Lira', 'TRY', 949, '₺'),
('Trinidad And Tobago Dollar', 'TTD', 780, '$'),
('New Taiwan Dollar', 'TWD', 901, 'NT$'),
('Tanzanian Shilling', 'TZS', 834, 'TSh'),
('Ukrainian Hryvnia', 'UAH', 980, '₴'),
('Ugandan Shilling', 'UGX', 800, 'USh'),
('US Dollar', 'USD', 840, '$'),
('Uruguay Peso En Unidades Indexadas', 'UYI', 940, ''),
('Uruguayan Peso', 'UYU', 858, '$U'),
('Uzbekistan Som', 'UZS', 860, 'сўм'),
('Venezuelan Bolívar Soberano', 'VES', 928, 'Bs.S'),
('Vietnamese Dong', 'VND', 704, '₫'),
('Vanuatu Vatu', 'VUV', 548, 'VT'),
('Samoan Tala', 'WST', 882, 'WS$'),
('Special Drawing Rights', 'XDR', 960, ''),
-- ('European Composite Unit (Eurco)', 'XBA', 955, ''),
-- ('European Monetary Unit (E.M.U.-6)', 'XBB', 956, ''),
-- ('European Unit Of Account 9 (E.U.A.-9)', 'XBC', 957, ''),
-- ('European Unit Of Account 17 (E.U.A.-17)', 'XBD', 958, ''),
-- ('European Currency Unit', 'XEU', 999, '') -- removed (withdrawn)
('Gold', 'XAU', 959, ''),
('Palladium', 'XPD', 964, ''),
('Platinum', 'XPT', 962, ''),
('Silver', 'XAG', 961, ''),
('Yemeni Rial', 'YER', 886, '﷼'),
('South African Rand', 'ZAR', 710, 'R'),
('Zambian Kwacha', 'ZMW', 967, 'K'),
('Zimbabwe Gold', 'ZWG', 924, 'ZiG');