CREATE TYPE DISPLAY_TYPE AS ENUM ('SEPARATE_CURRENCIES', 'BASE_CURRENCY');

CREATE TABLE IF NOT EXISTS SETTINGS
(
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID NOT NULL REFERENCES USERS (ID),

    DISPLAY_TYPE DISPLAY_TYPE NOT NULL DEFAULT 'SEPARATE_CURRENCIES',
    
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_settings_updated_at
BEFORE UPDATE ON settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();









